# Generated by Django 4.1.7 on 2023-05-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMDApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
