# Generated by Django 4.1.7 on 2023-05-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMDApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppea',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
