# Generated by Django 4.1.7 on 2023-05-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMDApp', '0002_alter_turno_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='state',
            field=models.CharField(default='solicited', max_length=10),
        ),
    ]
