# Generated by Django 4.1.7 on 2023-05-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMDApp', '0002_alter_ppea_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppea',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
