# Generated by Django 4.1.7 on 2023-03-22 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OMDApp', '0003_customuser_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
