# Generated by Django 4.1.7 on 2023-05-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMDApp', '0003_turno_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='state',
            field=models.CharField(default='S', max_length=10),
        ),
    ]
