# Generated by Django 4.1.7 on 2023-05-18 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OMDApp', '0004_alter_turno_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OMDApp.veterinario'),
        ),
        migrations.AddField(
            model_name='turno',
            name='solicited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
