# Generated by Django 4.1.7 on 2023-05-18 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OMDApp', '0005_turno_accepted_by_turno_solicited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='solicited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
