# Generated by Django 4.1.7 on 2023-03-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMDApp', '0006_alter_customuser_options_veterinario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_confirmed',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
