# Generated by Django 4.1.7 on 2023-04-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OMDApp', '0007_remove_customuser_email_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('is_client', 'Correspondiente al rol de Cliente en la documentación')]},
        ),
        migrations.AlterModelOptions(
            name='veterinario',
            options={'permissions': [('is_vet', 'Correspondiente al rol de Veterinario en la documentación')]},
        ),
    ]
